# Generated by Django 2.0.7 on 2019-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierid', models.CharField(default='1SUP', max_length=10)),
                ('suppliername', models.CharField(default='xxx', max_length=25)),
                ('address', models.TextField(default='xxx')),
                ('supplierphonenumber', models.PositiveIntegerField(default='91')),
                ('emailid', models.CharField(default='xxxxx@xxxxx.com', max_length=15)),
                ('medicinedealership', models.CharField(default='xxx', max_length=15)),
            ],
        ),
    ]
