# Generated by Django 2.0.7 on 2019-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplierphonenumber',
            field=models.CharField(default='+91', max_length=12),
        ),
    ]
