# Generated by Django 2.0.7 on 2019-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20190917_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email_id',
            field=models.CharField(default='xxxxx@xxxxx.com', max_length=25),
        ),
    ]
