# Generated by Django 2.0.7 on 2019-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20190922_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email_id',
            field=models.CharField(default='xxxxx@xxxxx.com', max_length=35),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(default='xxx', max_length=25),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_contactno',
            field=models.CharField(default='080-', max_length=12),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(default='1SID', max_length=10),
        ),
    ]
