# Generated by Django 2.0.7 on 2019-10-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20190922_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='email_id',
            new_name='supplier_email_id',
        ),
    ]
