# Generated by Django 2.0.7 on 2019-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20191013_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(default='SUPPID', max_length=10, primary_key=True, serialize=False),
        ),
    ]
