# Generated by Django 2.0.7 on 2019-12-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_auto_20191013_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(default='SID', max_length=10, primary_key=True, serialize=False),
        ),
    ]
