# Generated by Django 2.0.7 on 2019-10-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicineinventory', '0016_auto_20191013_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_medicine',
            fields=[
                ('bill_no', models.CharField(default='BNO', max_length=10, primary_key=True, serialize=False)),
                ('medicine_quantity', models.PositiveIntegerField(default='1')),
                ('medicine_price', models.DecimalField(decimal_places=2, default='0000.00', max_digits=1000)),
                ('bill_amount', models.DecimalField(decimal_places=2, default='00000.00', max_digits=10000)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicineinventory.medicineinventory')),
            ],
        ),
    ]
