# Generated by Django 2.0.7 on 2019-10-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_medicine', '0002_auto_20191013_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_medicine',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill_medicine',
            name='bill_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill'),
        ),
    ]
