# Generated by Django 2.0.7 on 2019-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_medicine', '0003_auto_20191013_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_medicine',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default='0000.00', max_digits=1000),
        ),
    ]
