# Generated by Django 2.0.7 on 2019-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.CharField(default='1BNOxxxxxx', max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('itemid', models.PositiveIntegerField(default='0')),
                ('medicinename', models.CharField(default='xxx', max_length=15)),
                ('quantity', models.PositiveIntegerField(default='1')),
                ('price', models.DecimalField(decimal_places=2, default='00000.00', max_digits=10000)),
                ('tax', models.DecimalField(decimal_places=2, default='00.00', max_digits=50)),
            ],
        ),
    ]
