# Generated by Django 2.0.7 on 2019-09-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bills',
            new_name='bill',
        ),
    ]
