# Generated by Django 2.0.7 on 2019-09-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20190915_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date',
        ),
    ]
