# Generated by Django 2.0.7 on 2019-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0000.00', max_digits=1000),
        ),
    ]
