# Generated by Django 2.0.7 on 2019-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20190917_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='bill_date',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='billnumber',
            new_name='bill_no',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='medicinename',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax',
        ),
        migrations.AddField(
            model_name='bill',
            name='doctor_name',
            field=models.CharField(default='Dr.xxx', max_length=15),
        ),
    ]
