# Generated by Django 2.0.7 on 2019-10-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_auto_20191006_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(default='1BNOxxxxxx', max_length=10, primary_key=True, serialize=False),
        ),
    ]
