# Generated by Django 2.0.7 on 2019-10-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_auto_20191013_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(default='1BNO', max_length=10, primary_key=True, serialize=False),
        ),
    ]
