# Generated by Django 2.0.7 on 2019-10-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_auto_20191013_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default='00000.00', max_digits=10000),
        ),
    ]
