# Generated by Django 2.0.7 on 2019-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_bill_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='doctor_name',
            field=models.CharField(default='Dr.xxx', max_length=15),
        ),
    ]
