# Generated by Django 2.0.7 on 2019-10-06 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_group', '0002_auto_20191006_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine_group',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='medicine_group',
            name='type_of_medicine',
        ),
        migrations.AddField(
            model_name='medicine_group',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_group',
            name='medicine_group',
            field=models.CharField(default='xxx', max_length=20),
        ),
    ]
