# Generated by Django 2.0.7 on 2019-10-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_group', '0003_auto_20191006_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine_group',
            old_name='taxes',
            new_name='medicine_tax',
        ),
        migrations.RenameField(
            model_name='medicine_group',
            old_name='effective_date',
            new_name='tax_effective_date',
        ),
    ]
