# Generated by Django 2.0.7 on 2019-10-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_group', '0004_auto_20191006_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine_group',
            old_name='medicine_group',
            new_name='medicine_groups',
        ),
    ]
