# Generated by Django 2.0.7 on 2019-10-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_group', '0005_auto_20191013_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine_group',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicine_group',
            name='medicine_groups',
            field=models.CharField(default='xxx', max_length=20, primary_key=True, serialize=False),
        ),
    ]
