# Generated by Django 2.0.7 on 2019-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentorder', models.CharField(default='1POR', max_length=10)),
                ('amountpaid', models.DecimalField(decimal_places=2, default='00000.00', max_digits=10000)),
                ('paymentdetails', models.CharField(default='xxx', max_length=15)),
            ],
        ),
    ]
