# Generated by Django 2.0.7 on 2019-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amountpaid',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentorder',
            new_name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase_order',
            field=models.CharField(default='1PRO', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier_id',
            field=models.CharField(default='1SUP', max_length=10),
        ),
    ]
