# Generated by Django 2.0.7 on 2019-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20191006_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='1POR', max_length=10, primary_key=True, serialize=False),
        ),
    ]
