# Generated by Django 2.0.7 on 2019-10-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20191013_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='purchase_orderno',
        ),
    ]
