# Generated by Django 2.0.7 on 2019-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_purchase_orderno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='PYID', max_length=10, primary_key=True, serialize=False),
        ),
    ]
