# Generated by Django 2.0.7 on 2019-11-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20191014_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_details',
            field=models.CharField(default='Cheque/DD/NEFT', max_length=25),
        ),
    ]
