# Generated by Django 2.0.7 on 2019-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='items',
            new_name='itemname',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoicevalue',
        ),
        migrations.AddField(
            model_name='invoice',
            name='dateofissue',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoicequantity',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
