# Generated by Django 2.0.7 on 2019-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20190917_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='dateofissue',
            new_name='invoice_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceno',
            new_name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoicequantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxes',
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_id',
            field=models.CharField(default='1SUP', max_length=10),
        ),
    ]
