# Generated by Django 2.0.7 on 2019-10-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20190917_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
