# Generated by Django 2.0.7 on 2019-10-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20191006_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='1INV', max_length=10, primary_key=True, serialize=False),
        ),
    ]
