# Generated by Django 2.0.7 on 2019-09-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('login', models.TimeField(auto_now=True)),
                ('logout', models.TimeField(auto_now=True)),
            ],
        ),
    ]
