# Generated by Django 2.0.7 on 2019-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='login',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='logout',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
