# Generated by Django 2.0.7 on 2019-10-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190917_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
