# Generated by Django 2.0.7 on 2019-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login',
            field=models.DateTimeField(),
        ),
    ]
