# Generated by Django 2.0.7 on 2019-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191006_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='date',
        ),
        migrations.RemoveField(
            model_name='login',
            name='time',
        ),
        migrations.AlterField(
            model_name='login',
            name='login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='logout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
