# Generated by Django 2.0.7 on 2019-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191006_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='login',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
