# Generated by Django 2.0.7 on 2019-10-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191006_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='login',
        ),
    ]
