# Generated by Django 2.0.7 on 2019-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_login_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
