# Generated by Django 2.0.7 on 2019-10-06 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191006_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 17, 6, 2, 325263)),
        ),
    ]
