# Generated by Django 2.0.7 on 2019-10-06 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20191006_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='login',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 17, 10, 34, 873754)),
        ),
        migrations.AlterField(
            model_name='login',
            name='logout',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 17, 10, 34, 873754)),
        ),
        migrations.AlterField(
            model_name='login',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
