# Generated by Django 2.0.7 on 2019-10-06 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20191006_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='login',
            name='logout',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 17, 15, 13, 50128)),
        ),
    ]
