# Generated by Django 2.0.7 on 2019-10-06 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20191006_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='logout',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
