# Generated by Django 2.0.7 on 2019-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(default='1INV', max_length=10)),
                ('medicine_id', models.CharField(default='1MED', max_length=10)),
                ('medicine_quantity', models.PositiveIntegerField(default='1')),
                ('medicine_price', models.DecimalField(decimal_places=2, default='0000.00', max_digits=1000)),
                ('medicine_tax', models.DecimalField(decimal_places=2, default='00.00', max_digits=50)),
            ],
        ),
    ]
