# Generated by Django 2.0.7 on 2019-10-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_medicine',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicineinventory.medicineinventory'),
        ),
    ]
