# Generated by Django 2.0.7 on 2019-10-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_medicine', '0002_auto_20191006_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_medicine',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
    ]
