# Generated by Django 2.0.7 on 2019-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_medicine', '0003_auto_20191013_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_medicine',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice_medicine',
            name='invoice_no',
            field=models.CharField(default='1INV', max_length=10, primary_key=True, serialize=False),
        ),
    ]
