# Generated by Django 2.0.7 on 2019-10-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_medicine', '0005_auto_20191013_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_medicine',
            old_name='medicine_price',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='invoice_medicine',
            old_name='medicine_quantity',
            new_name='unit_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice_medicine',
            name='medicine_tax',
        ),
        migrations.AddField(
            model_name='invoice_medicine',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice_medicine',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
    ]
