# Generated by Django 2.0.7 on 2019-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_medicine', '0006_auto_20191013_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_medicine',
            name='additional_tax',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=50),
        ),
    ]
