# Generated by Django 2.0.7 on 2019-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchaseorder',
            new_name='purchase_order',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='medicine_id',
            field=models.CharField(default='1MED', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.CharField(default='1SUP', max_length=10),
        ),
    ]
