# Generated by Django 2.0.7 on 2019-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0002_auto_20190917_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_order',
            new_name='purchase_orderno',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_orderdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipment_address',
            field=models.TextField(default=50),
        ),
    ]
