# Generated by Django 2.0.7 on 2019-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0004_auto_20191006_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipment_address',
            field=models.TextField(default='Enter shipment address'),
        ),
    ]
