# Generated by Django 2.0.7 on 2019-10-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0005_auto_20191006_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
