# Generated by Django 2.0.7 on 2019-10-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0006_auto_20191006_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_orderno',
            field=models.CharField(default='1PRO', max_length=10, primary_key=True, serialize=False),
        ),
    ]
