# Generated by Django 2.0.7 on 2019-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0008_auto_20191013_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_orderno',
            field=models.CharField(default='PURNO', max_length=10, primary_key=True, serialize=False),
        ),
    ]
