# Generated by Django 2.0.7 on 2019-11-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0009_auto_20191013_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipment_address',
            field=models.CharField(default='Enter shipment address', max_length=100),
        ),
    ]
