# Generated by Django 2.0.7 on 2019-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_orderno', models.CharField(default='1PRO', max_length=10)),
                ('medicine_id', models.CharField(default='1MED', max_length=10)),
                ('purchase_quantity', models.PositiveIntegerField(default='1')),
                ('purchase_tax', models.DecimalField(decimal_places=2, default='00.00', max_digits=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, default='00000.00', max_digits=10000)),
            ],
        ),
    ]
