# Generated by Django 2.0.7 on 2019-10-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_detail',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicineinventory.medicineinventory'),
        ),
    ]
