# Generated by Django 2.0.7 on 2019-10-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_detail', '0002_auto_20191006_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_detail',
            name='purchase_orderno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.purchaseorder'),
        ),
    ]
