# Generated by Django 2.0.7 on 2019-10-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_detail', '0003_auto_20191013_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='purchase_orderno',
            field=models.CharField(default='1PRO', max_length=10, primary_key=True, serialize=False),
        ),
    ]
