# Generated by Django 2.0.7 on 2019-10-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_detail', '0005_auto_20191013_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_detail',
            old_name='purchase_price',
            new_name='total_purchase_amount',
        ),
        migrations.RenameField(
            model_name='purchase_detail',
            old_name='purchase_quantity',
            new_name='unit_quantity',
        ),
        migrations.RemoveField(
            model_name='purchase_detail',
            name='purchase_tax',
        ),
        migrations.AddField(
            model_name='purchase_detail',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='purchase_orderno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.purchaseorder'),
        ),
    ]
