# Generated by Django 2.0.7 on 2019-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicineinventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineid', models.CharField(default='1MED', max_length=10)),
                ('medicinename', models.CharField(default='xxx', max_length=25)),
                ('typeofmedicine', models.CharField(default='xxx', max_length=15)),
                ('quantityonhand', models.PositiveIntegerField(default='0')),
                ('reorderlevel', models.PositiveIntegerField(default='1')),
                ('reorderquantity', models.PositiveIntegerField(default='1')),
                ('price', models.DecimalField(decimal_places=2, default='00000.00', max_digits=10000)),
            ],
        ),
    ]
