# Generated by Django 2.0.7 on 2019-09-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='medicineid',
            new_name='medicine_id',
        ),
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='medicinename',
            new_name='medicine_name',
        ),
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='quantityonhand',
            new_name='quantity_on_hand',
        ),
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='reorderlevel',
            new_name='reorder_level',
        ),
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='reorderquantity',
            new_name='reorder_quantity',
        ),
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='typeofmedicine',
            new_name='type_of_medicine',
        ),
    ]
