# Generated by Django 2.0.7 on 2019-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0002_auto_20190917_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinventory',
            name='supplier_id',
            field=models.CharField(default='1SUP', max_length=10),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='tax',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=50),
        ),
    ]
