# Generated by Django 2.0.7 on 2019-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0003_auto_20190917_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='supplier_id',
            field=models.CharField(default='1SUP', max_length=25),
        ),
    ]
