# Generated by Django 2.0.7 on 2019-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0005_auto_20190922_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='medicine_id',
            field=models.CharField(default='MID', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='medicine_name',
            field=models.CharField(default='xxx', max_length=35),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='supplier_id',
            field=models.CharField(default='SID', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='type_of_medicine',
            field=models.CharField(default='xxx', max_length=25),
        ),
    ]
