# Generated by Django 2.0.7 on 2019-10-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0006_auto_20190922_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineinventory',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='type_of_medicine',
        ),
    ]
