# Generated by Django 2.0.7 on 2019-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0008_medicineinventory_medicine_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='price',
            new_name='medicine_price',
        ),
    ]
