# Generated by Django 2.0.7 on 2019-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0010_auto_20191006_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineinventory',
            old_name='medicine_group',
            new_name='medicine_groups',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='medicine_id',
            field=models.CharField(default='MID', max_length=10, primary_key=True, serialize=False),
        ),
    ]
