# Generated by Django 2.0.7 on 2019-10-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0012_auto_20191013_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='medicine_groups',
            field=models.CharField(default='xxx', max_length=20),
        ),
    ]
