# Generated by Django 2.0.7 on 2019-10-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0013_auto_20191013_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineinventory',
            name='supplier_id',
        ),
    ]
