# Generated by Django 2.0.7 on 2019-10-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20191013_1616'),
        ('medicineinventory', '0014_remove_medicineinventory_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinventory',
            name='supplier_id',
            field=models.ForeignKey(default='SID', on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
            preserve_default=False,
        ),
    ]
