# Generated by Django 2.0.7 on 2019-10-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0015_medicineinventory_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='medicine_groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_group.medicine_group'),
        ),
    ]
