# Generated by Django 2.0.7 on 2019-11-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicineinventory', '0017_auto_20191115_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='supplier_id',
            field=models.ForeignKey(default='SUPPID', on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
